export const courseSections = [
  // Модуль 1
  { type: "lesson", id: "lesson-1.1", moduleid:"module-1" },
  { type: "quiz", id: "quiz-1.1", moduleid:"module-1" },
  { type: "lesson", id: "lesson-1.2", moduleid:"module-1" },
  { type: "practice", id: "practice-1.2", moduleid:"module-1" },
  { type: "lesson", id: "lesson-1.3", moduleid:"module-1" },
  { type: "practice", id: "practice-1.3", moduleid:"module-1" },
  { type: "lesson", id: "lesson-1.4", moduleid:"module-1" },
  { type: "practice", id: "practice-1.4", moduleid:"module-1" },
  { type: "lesson", id: "lesson-1.5", moduleid:"module-1" },
  { type: "practice", id: "practice-1.5", moduleid:"module-1" },
  { type: "quiz", id: "quiz-1-final", moduleid:"module-1" },
  { type: "task", id: "task-1", moduleid:"module-1" },

  // Модуль 2
  { type: "lesson", id: "lesson-2.1", moduleid:"module-2" },
  { type: "practice", id: "practice-2.1", moduleid:"module-2" },
  { type: "lesson", id: "lesson-2.2", moduleid:"module-2" },
  { type: "quiz", id: "quiz-2.2", moduleid:"module-2" },
  { type: "practice", id: "practice-2.2", moduleid:"module-2" },
  { type: "lesson", id: "lesson-2.3", moduleid:"module-2" },
  { type: "practice", id: "practice-2.3", moduleid:"module-2" },
  { type: "lesson", id: "lesson-2.4", moduleid:"module-2" },
  { type: "practice", id: "practice-2.4", moduleid:"module-2" },
  { type: "lesson", id: "lesson-2.5", moduleid:"module-2" },
  { type: "practice", id: "practice-2.5", moduleid:"module-2" },
  { type: "quiz", id: "quiz-2-final", moduleid:"module-2" },
  { type: "task", id: "task-2", moduleid:"module-2" },

  // Модуль 3
  { type: "lesson", id: "lesson-3.1", moduleid:"module-3" },
  { type: "practice", id: "practice-3.1", moduleid:"module-3" },
  { type: "lesson", id: "lesson-3.2", moduleid:"module-3" },
  { type: "quiz", id: "quiz-3.2", moduleid:"module-3" },
  { type: "practice", id: "practice-3.2", moduleid:"module-3" },
  { type: "lesson", id: "lesson-3.3", moduleid:"module-3" },
  { type: "practice", id: "practice-3.3", moduleid:"module-3" },
  { type: "lesson", id: "lesson-3.4", moduleid:"module-3" },
  { type: "quiz", id: "quiz-3.4", moduleid:"module-3" },
  { type: "practice", id: "practice-3.4", moduleid:"module-3" },
  { type: "lesson", id: "lesson-3.5", moduleid:"module-3" },
  { type: "practice", id: "practice-3.5", moduleid:"module-3" },
  { type: "quiz", id: "quiz-3-final", moduleid:"module-3" },
  { type: "task", id: "task-3", moduleid:"module-3" },

  // Модуль 4
  { type: "lesson", id: "lesson-4.1", moduleid:"module-4" },
  { type: "practice", id: "practice-4.1", moduleid:"module-4" },
  { type: "lesson", id: "lesson-4.2", moduleid:"module-4" },
  { type: "quiz", id: "quiz-4.2", moduleid:"module-4" },
  { type: "practice", id: "practice-4.2", moduleid:"module-4" },
  { type: "lesson", id: "lesson-4.3", moduleid:"module-4" },
  { type: "practice", id: "practice-4.3", moduleid:"module-4" },
  { type: "lesson", id: "lesson-4.4", moduleid:"module-4" },
  { type: "quiz", id: "quiz-4.4", moduleid:"module-4" },
  { type: "practice", id: "practice-4.4", moduleid:"module-4" },
  { type: "lesson", id: "lesson-4.5", moduleid:"module-4" },
  { type: "practice", id: "practice-4.5", moduleid:"module-4" },
  { type: "quiz", id: "quiz-4-final", moduleid:"module-4" },
  { type: "task", id: "task-4", moduleid:"module-4" },

  // Модуль 5
  { type: "lesson", id: "lesson-5.1", moduleid:"module-5" },
  { type: "quiz", id: "quiz-5.1", moduleid:"module-5" },
  { type: "practice", id: "practice-5.1", moduleid:"module-5" },
  { type: "lesson", id: "lesson-5.2", moduleid:"module-5" },
  { type: "practice", id: "practice-5.2", moduleid:"module-5" },
  { type: "lesson", id: "lesson-5.3", moduleid:"module-5" },
  { type: "quiz", id: "quiz-5.3", moduleid:"module-5" },
  { type: "practice", id: "practice-5.3", moduleid:"module-5" },
  { type: "lesson", id: "lesson-5.4", moduleid:"module-5" },
  { type: "practice", id: "practice-5.4", moduleid:"module-5" },
  { type: "lesson", id: "lesson-5.5", moduleid:"module-5" },
  { type: "practice", id: "practice-5.5", moduleid:"module-5" },
  { type: "quiz", id: "quiz-5-final", moduleid:"module-5" },
  { type: "task", id: "task-5", moduleid:"module-5" },

  // Модуль 6
  { type: "lesson", id: "lesson-6.1", moduleid:"module-6" },
  { type: "quiz", id: "quiz-6.1", moduleid:"module-6" },
  { type: "practice", id: "practice-6.1", moduleid:"module-6" },
  { type: "lesson", id: "lesson-6.2", moduleid:"module-6" },
  { type: "practice", id: "practice-6.2", moduleid:"module-6" },
  { type: "lesson", id: "lesson-6.3", moduleid:"module-6" },
  { type: "quiz", id: "quiz-6.3", moduleid:"module-6" },
  { type: "practice", id: "practice-6.3", moduleid:"module-6" },
  { type: "lesson", id: "lesson-6.4", moduleid:"module-6" },
  { type: "practice", id: "practice-6.4", moduleid:"module-6" },
  { type: "lesson", id: "lesson-6.5", moduleid:"module-6" },
  { type: "quiz", id: "quiz-6-final", moduleid:"module-6" },
  { type: "task", id: "task-6", moduleid:"module-6" },

  // Итоговые страницы после всех модулей/заданий:
  { type: "summary", id: "summary", moduleid: "final", title: "Подведение итогов" },
  { type: "achievements", id: "achievements", moduleid: "final", title: "Достижения" },
  { type: "certificate", id: "certificate", moduleid: "final", title: "Сертификат" }
];
