export const practice = [
    {
      id: "practice-1.2",
      title: "Построение структуры проекта",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice1_2.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice1_2_pin.md?raw"),
    },
    {
      id: "practice-1.3",
      title: "Изучаем интерфейс Final Cut Pro X",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice1_3.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice1_3_pin.md?raw"),
    },
    {
      id: "practice-1.4",
      title: "Импорт и организация медиа в FCPX",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice1_4.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice1_4_pin.md?raw"),
    },
    {
      id: "practice-1.5",
      title: "Горячие клавиши и производительность",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice1_5.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice1_5_pin.md?raw"),
    },
    {
      id: "practice-2.1",
      title: "Добавление и перемещение клипов",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice2_1.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice2_1_pin.md?raw"),
    },
    {
      id: "practice-2.2",
      title: "Нарезка и управление клипами на таймлинии",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice2_2.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice2_2_pin.md?raw"),
    },
    {
      id: "practice-2.3",
      title: "Монтаж по ритму в Final Cut Pro X",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice2_3.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice2_3_pin.md?raw"),
    },
    {
      id: "practice-2.4",
      title: "Storylines и Compound Clips",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice2_4.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice2_4_pin.md?raw"),
    },
    {
      id: "practice-2.5",
      title: "Применение простых переходов",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice2_5.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice2_5_pin.md?raw"),
    },
    {
      id: "practice-3.1",
      title: "Работа с типами аудио и ролями",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice3_1.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice3_1_pin.md?raw"),
    },
    {
      id: "practice-3.2",
      title: "Выравнивание громкости и стереобаланса",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice3_2.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice3_2_pin.md?raw"),
    },
    {
      id: "practice-3.3",
      title: "Шумоподавление и эквалайзер",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice3_3.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice3_3_pin.md?raw"),
    },
    {
      id: "practice-3.4",
      title: "Ducking с помощью ключевых кадров",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice3_4.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice3_4_pin.md?raw"),
    },
    {
      id: "practice-3.5",
      title: "Синхронизация видео и внешнего звука",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice3_5.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice3_5_pin.md?raw"),
    },
    {
      id: "practice-4.1",
      title: "Настройка баланса белого и экспозиции",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice4_1.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice4_1_pin.md?raw"),
    },
    {
      id: "practice-4.2",
      title: "Цветокоррекция с помощью колёс и кривых",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice4_2.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice4_2_pin.md?raw"),
    },
    {
      id: "practice-4.3",
      title: "Применение LUT и сравнение с ручной коррекцией",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice4_3.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice4_3_pin.md?raw"),
    },
    {
      id: "practice-4.4",
      title: "Применение эффектов и фильтров",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice4_4.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice4_4_pin.md?raw"),
    },
    {
      id: "practice-4.5",
      title: "Стилизация сцены под moodboard или референс",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice4_5.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice4_5_pin.md?raw"),
    },
    {
      id: "practice-5.1",
      title: "Добавление пользовательского шаблона Motion в Final Cut Pro",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice5_1.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice5_1_pin.md?raw"),
    },
    {
      id: "practice-5.2",
      title: "Добавление и настройка шаблона титра или нижней трети",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice5_2.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice5_2_pin.md?raw"),
    },
    {
      id: "practice-5.3",
      title: "Анимация простого объекта в Motion",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice5_3.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice5_3_pin.md?raw"),
    },
    {
      id: "practice-5.4",
      title: "Анимация с использованием keyframes",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice5_4.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice5_4_pin.md?raw"),
    },
    {
      id: "practice-5.5",
      title: "Создание и импорт пользовательского шаблона в Final Cut Pro",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice5_5.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice5_5_pin.md?raw"),
    },
    {
      id: "practice-6.1",
      title: "Экспорт проекта в H.264 и ProRes",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice6_1.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice6_1_pin.md?raw"),
    },
    {
      id: "practice-6.2",
      title: "Отправка проекта в Apple Compressor и создание собственного пресета",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice6_2.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice6_2_pin.md?raw"),
    },
    {
      id: "practice-6.3",
      title: "Создание и использование пресета под соцсети",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice6_3.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice6_3_pin.md?raw"),
    },
    {
      id: "practice-6.4",
      title: "Финальный контроль качества видео перед публикацией",
      markdown: () => import("../../../Content/FCPXZeroPractice/Practice6_4.md?raw"),
      pin: () => import("../../../Content/FCPXZeroPractice/Practice6_4_pin.md?raw"),
    }
  ];